name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet Packages
      run: nuget restore TestActionMain\TestActionMain.sln
      
    - name: Restore Packages AppMain
      id: restoreAppMain
      run: nuget restore AppMain.sln
      env:
        nuget-version: 6.x

    - name: Build Dll
      run: msbuild TestActionMain\Dll.csproj /p:Configuration=Release /p:Platform="AnyCPU"

    - name: Build AppMain
      run: msbuild AppMain\AppMain.csproj /p:Configuration=Release /p:Platform="AnyCPU"    

    - name: Archive Executable
      run: |
        mkdir artifacts
        cp AppMain/bin/Release/* artifacts/
        zip -r artifacts.zip artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: ./artifacts.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
